# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66c8bb5ab104c0918b7655cc98869803959c7a6740a3b9fe01533517a518db1fc720e58a6d83a0d5c5707cd36c9f4a2a6bc71c90e7a0687d6e6c9f473bc2418

test:
  secret_key_base: d9e1825526b6a6ca4240ce2136c63f331bf223a1fd4b294d2e11e5c8862287ce63666e06fd40121db4db63c851d3b90e3083f801b673b90dab1ece095e20d451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
